DELETE FROM countries;
ALTER TABLE countries DROP COLUMN IF EXISTS alpha2;
ALTER TABLE countries DROP COLUMN IF EXISTS alpha3;
ALTER TABLE countries DROP COLUMN IF EXISTS numeric;
ALTER TABLE countries ADD COLUMN name JSONB NOT NULL DEFAULT '[]';
