[server]
host = "0.0.0.0"
port = 8000
database = "postgresql://delivery:delivery@delivery-pg/delivery"
thread_count = 20

[client]
http_client_buffer_size=3
http_client_retries=3
dns_worker_thread_count=4
timeout_duration_ms=5000
