[server]
host = "0.0.0.0"
port = 8000
database = "postgresql://delivery:delivery@delivery-pg/delivery"
redis = "redis://delivery-redis"
thread_count = 20

[client]
http_client_buffer_size=3
http_client_retries=3
dns_worker_thread_count=4
http_timeout_ms=5000
