DELETE FROM countries ;

INSERT INTO countries (label, level, alpha3) VALUES ('All', 0, 'XAL');
INSERT INTO countries (parent, label, level, alpha3) VALUES ('XAL', 'Africa', 1, 'XAF');
INSERT INTO countries (parent, label, level, alpha3) VALUES ('XAL', 'Asia', 1, 'XAS');
INSERT INTO countries (parent, label, level, alpha3) VALUES ('XAL', 'Oceania and Australia', 1, 'XOC');
INSERT INTO countries (parent, label, level, alpha3) VALUES ('XAL', 'Europe', 1, 'XEU');
INSERT INTO countries (parent, label, level, alpha3) VALUES ('XAL', 'North America', 1, 'XNA');
INSERT INTO countries (parent, label, level, alpha3) VALUES ('XAL', 'South America', 1, 'XSA');
INSERT INTO countries (parent, label, level, alpha3) VALUES ('XAL', 'Antarctica', 1, 'XAN');

INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'AF', 	'AFG', 	004, 	'Afghanistan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'AL', 	'ALB', 	008, 	'Albania', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAN', 	'AQ', 	'ATA', 	010, 	'Antarctica (the territory South of 60 deg S)', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'DZ', 	'DZA', 	012, 	'Algeria', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'AS', 	'ASM', 	016, 	'American Samoa', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'AD', 	'AND', 	020, 	'Andorra', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'AO', 	'AGO', 	024, 	'Angola', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'AG', 	'ATG', 	028, 	'Antigua and Barbuda', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'AZ', 	'AZE', 	031, 	'Azerbaijan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'AR', 	'ARG', 	032, 	'Argentina', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'AU', 	'AUS', 	036, 	'Australia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'AT', 	'AUT', 	040, 	'Austria', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'BS', 	'BHS', 	044, 	'Bahamas', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'BH', 	'BHR', 	048, 	'Bahrain', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'BD', 	'BGD', 	050, 	'Bangladesh', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'AM', 	'ARM', 	051, 	'Armenia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'BB', 	'BRB', 	052, 	'Barbados', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'BE', 	'BEL', 	056, 	'Belgium', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'BM', 	'BMU', 	060, 	'Bermuda', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'BT', 	'BTN', 	064, 	'Bhutan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'BO', 	'BOL', 	068, 	'Bolivia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'BA', 	'BIH', 	070, 	'Bosnia and Herzegovina', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'BW', 	'BWA', 	072, 	'Botswana', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAN', 	'BV', 	'BVT', 	074, 	'Bouvet Island (Bouvetoya)', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'BR', 	'BRA', 	076, 	'Brazil', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'BZ', 	'BLZ', 	084, 	'Belize', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'IO', 	'IOT', 	086, 	'British Indian Ocean Territory (Chagos Archipelago)', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'SB', 	'SLB', 	090, 	'Solomon Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'VG', 	'VGB', 	092, 	'British Virgin Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'BN', 	'BRN', 	096, 	'Brunei Darussalam', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'BG', 	'BGR', 	100, 	'Bulgaria', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'MM', 	'MMR', 	104, 	'Myanmar', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'BI', 	'BDI', 	108, 	'Burundi', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'BY', 	'BLR', 	112, 	'Belarus', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'KH', 	'KHM', 	116, 	'Cambodia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'CM', 	'CMR', 	120, 	'Cameroon', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'CA', 	'CAN', 	124, 	'Canada', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'CV', 	'CPV', 	132, 	'Cape Verde', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'KY', 	'CYM', 	136, 	'Cayman Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'CF', 	'CAF', 	140, 	'Central African Republic', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'LK', 	'LKA', 	144, 	'Sri Lanka', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'TD', 	'TCD', 	148, 	'Chad', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'CL', 	'CHL', 	152, 	'Chile', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'CN', 	'CHN', 	156, 	'China', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'TW', 	'TWN', 	158, 	'Taiwan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'CX', 	'CXR', 	162, 	'Christmas Island', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'CC', 	'CCK', 	166, 	'Cocos (Keeling) Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'CO', 	'COL', 	170, 	'Colombia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'KM', 	'COM', 	174, 	'Comoros', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'YT', 	'MYT', 	175, 	'Mayotte', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'CG', 	'COG', 	178, 	'Congo - Brazzaville', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'CD', 	'COD', 	180, 	'Congo - Kinshasa', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'CK', 	'COK', 	184, 	'Cook Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'CR', 	'CRI', 	188, 	'Costa Rica', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'HR', 	'HRV', 	191, 	'Croatia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'CU', 	'CUB', 	192, 	'Cuba', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'CY', 	'CYP', 	196, 	'Cyprus', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'CZ', 	'CZE', 	203, 	'Czech Republic', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'BJ', 	'BEN', 	204, 	'Benin', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'DK', 	'DNK', 	208, 	'Denmark', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'DM', 	'DMA', 	212, 	'Dominica', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'DO', 	'DOM', 	214, 	'Dominican Republic', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'EC', 	'ECU', 	218, 	'Ecuador', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'SV', 	'SLV', 	222, 	'El Salvador', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'GQ', 	'GNQ', 	226, 	'Equatorial Guinea', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'ET', 	'ETH', 	231, 	'Ethiopia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'ER', 	'ERI', 	232, 	'Eritrea', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'EE', 	'EST', 	233, 	'Estonia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'FO', 	'FRO', 	234, 	'Faroe Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'FK', 	'FLK', 	238, 	'Falkland Islands (Malvinas)', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAN', 	'GS', 	'SGS', 	239, 	'South Georgia and the South Sandwich Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'FJ', 	'FJI', 	242, 	'Fiji', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'FI', 	'FIN', 	246, 	'Finland', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'AX', 	'ALA', 	248, 	'Åland Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'FR', 	'FRA', 	250, 	'France', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'GF', 	'GUF', 	254, 	'French Guiana', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'PF', 	'PYF', 	258, 	'French Polynesia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAN', 	'TF', 	'ATF', 	260, 	'French Southern Territories', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'DJ', 	'DJI', 	262, 	'Djibouti', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'GA', 	'GAB', 	266, 	'Gabon', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'GE', 	'GEO', 	268, 	'Georgia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'GM', 	'GMB', 	270, 	'Gambia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'PS', 	'PSE', 	275, 	'Palestinian Territory, Occupied', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'DE', 	'DEU', 	276, 	'Germany', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'GH', 	'GHA', 	288, 	'Ghana', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'GI', 	'GIB', 	292, 	'Gibraltar', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'KI', 	'KIR', 	296, 	'Kiribati', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'GR', 	'GRC', 	300, 	'Greece', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'GL', 	'GRL', 	304, 	'Greenland', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'GD', 	'GRD', 	308, 	'Grenada', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'GP', 	'GLP', 	312, 	'Guadeloupe', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'GU', 	'GUM', 	316, 	'Guam', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'GT', 	'GTM', 	320, 	'Guatemala', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'GN', 	'GIN', 	324, 	'Guinea', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'GY', 	'GUY', 	328, 	'Guyana', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'HT', 	'HTI', 	332, 	'Haiti', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAN', 	'HM', 	'HMD', 	334, 	'Heard Island and McDonald Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'VA', 	'VAT', 	336, 	'Holy See (Vatican City State)', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'HN', 	'HND', 	340, 	'Honduras', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'HK', 	'HKG', 	344, 	'Hong Kong', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'HU', 	'HUN', 	348, 	'Hungary', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'IS', 	'ISL', 	352, 	'Iceland', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'IN', 	'IND', 	356, 	'India', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'ID', 	'IDN', 	360, 	'Indonesia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'IR', 	'IRN', 	364, 	'Iran', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'IQ', 	'IRQ', 	368, 	'Iraq', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'IE', 	'IRL', 	372, 	'Ireland', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'IL', 	'ISR', 	376, 	'Israel', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'IT', 	'ITA', 	380, 	'Italy', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'CI', 	'CIV', 	384, 	'Côte d`Ivoire', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'JM', 	'JAM', 	388, 	'Jamaica', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'JP', 	'JPN', 	392, 	'Japan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'KZ', 	'KAZ', 	398, 	'Kazakhstan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'JO', 	'JOR', 	400, 	'Jordan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'KE', 	'KEN', 	404, 	'Kenya', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'KP', 	'PRK', 	408, 	'Korea, North', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'KR', 	'KOR', 	410, 	'Korea, South', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'KW', 	'KWT', 	414, 	'Kuwait', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'KG', 	'KGZ', 	417, 	'Kyrgyzstan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'LA', 	'LAO', 	418, 	'Laos', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'LB', 	'LBN', 	422, 	'Lebanon', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'LS', 	'LSO', 	426, 	'Lesotho', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'LV', 	'LVA', 	428, 	'Latvia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'LR', 	'LBR', 	430, 	'Liberia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'LY', 	'LBY', 	434, 	'Libyan Arab Jamahiriya', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'LI', 	'LIE', 	438, 	'Liechtenstein', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'LT', 	'LTU', 	440, 	'Lithuania', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'LU', 	'LUX', 	442, 	'Luxembourg', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'MO', 	'MAC', 	446, 	'Macao', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'MG', 	'MDG', 	450, 	'Madagascar', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'MW', 	'MWI', 	454, 	'Malawi', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'MY', 	'MYS', 	458, 	'Malaysia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'MV', 	'MDV', 	462, 	'Maldives', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'ML', 	'MLI', 	466, 	'Mali', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'MT', 	'MLT', 	470, 	'Malta', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'MQ', 	'MTQ', 	474, 	'Martinique', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'MR', 	'MRT', 	478, 	'Mauritania', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'MU', 	'MUS', 	480, 	'Mauritius', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'MX', 	'MEX', 	484, 	'Mexico, United Mexican States', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'MC', 	'MCO', 	492, 	'Monaco', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'MN', 	'MNG', 	496, 	'Mongolia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'MD', 	'MDA', 	498, 	'Moldova', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'ME', 	'MNE', 	499, 	'Montenegro', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'MS', 	'MSR', 	500, 	'Montserrat', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'MA', 	'MAR', 	504, 	'Morocco', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'MZ', 	'MOZ', 	508, 	'Mozambique', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'OM', 	'OMN', 	512, 	'Oman', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'NA', 	'NAM', 	516, 	'Namibia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'NR', 	'NRU', 	520, 	'Nauru', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'NP', 	'NPL', 	524, 	'Nepal', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'NL', 	'NLD', 	528, 	'Netherlands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'AN', 	'ANT', 	530, 	'Netherlands Antilles', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'CW', 	'CUW', 	531, 	'Curaçao', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'AW', 	'ABW', 	533, 	'Aruba', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'SX', 	'SXM', 	534, 	'Sint Maarten (Netherlands)', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'BQ', 	'BES', 	535, 	'Bonaire, Sint Eustatius and Saba', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'NC', 	'NCL', 	540, 	'New Caledonia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'VU', 	'VUT', 	548, 	'Vanuatu', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'NZ', 	'NZL', 	554, 	'New Zealand', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'NI', 	'NIC', 	558, 	'Nicaragua', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'NE', 	'NER', 	562, 	'Niger', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'NG', 	'NGA', 	566, 	'Nigeria', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'NU', 	'NIU', 	570, 	'Niue', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'NF', 	'NFK', 	574, 	'Norfolk Island', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'NO', 	'NOR', 	578, 	'Norway', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'MP', 	'MNP', 	580, 	'Northern Mariana Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'UM', 	'UMI', 	581, 	'United States Minor Outlying Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'FM', 	'FSM', 	583, 	'Micronesia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'MH', 	'MHL', 	584, 	'Marshall Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'PW', 	'PLW', 	585, 	'Palau', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'PK', 	'PAK', 	586, 	'Pakistan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'PA', 	'PAN', 	591, 	'Panama', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'PG', 	'PNG', 	598, 	'Papua New Guinea', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'PY', 	'PRY', 	600, 	'Paraguay', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'PE', 	'PER', 	604, 	'Peru', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'PH', 	'PHL', 	608, 	'Philippines', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'PN', 	'PCN', 	612, 	'Pitcairn Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'PL', 	'POL', 	616, 	'Poland', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'PT', 	'PRT', 	620, 	'Portugal', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'GW', 	'GNB', 	624, 	'Guinea-Bissau', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'TL', 	'TLS', 	626, 	'Timor-Leste', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'PR', 	'PRI', 	630, 	'Puerto Rico', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'QA', 	'QAT', 	634, 	'Qatar', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'RE', 	'REU', 	638, 	'Reunion', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'RO', 	'ROU', 	642, 	'Romania', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'RU', 	'RUS', 	643, 	'Russian Federation', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'RW', 	'RWA', 	646, 	'Rwanda', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'BL', 	'BLM', 	652, 	'Saint Barthelemy', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'SH', 	'SHN', 	654, 	'Saint Helena', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'KN', 	'KNA', 	659, 	'Saint Kitts and Nevis', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'AI', 	'AIA', 	660, 	'Anguilla', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'LC', 	'LCA', 	662, 	'Saint Lucia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'MF', 	'MAF', 	663, 	'Saint Martin', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'PM', 	'SPM', 	666, 	'Saint Pierre and Miquelon', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'VC', 	'VCT', 	670, 	'Saint Vincent and the Grenadines', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'SM', 	'SMR', 	674, 	'San Marino', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'ST', 	'STP', 	678, 	'São Tomé and Príncipe', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'SA', 	'SAU', 	682, 	'Saudi Arabia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'SN', 	'SEN', 	686, 	'Senegal', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'RS', 	'SRB', 	688, 	'Serbia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'SC', 	'SYC', 	690, 	'Seychelles', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'SL', 	'SLE', 	694, 	'Sierra Leone', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'SG', 	'SGP', 	702, 	'Singapore', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'SK', 	'SVK', 	703, 	'Slovakia (Slovak Republic)', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'VN', 	'VNM', 	704, 	'Vietnam', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'SI', 	'SVN', 	705, 	'Slovenia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'SO', 	'SOM', 	706, 	'Somalia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'ZA', 	'ZAF', 	710, 	'South Africa', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'ZW', 	'ZWE', 	716, 	'Zimbabwe', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'ES', 	'ESP', 	724, 	'Spain', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'SS', 	'SSD', 	728, 	'South Sudan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'SD', 	'SDN', 	729, 	'Sudan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'EH', 	'ESH', 	732, 	'Western Sahara', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'SR', 	'SUR', 	740, 	'Suriname', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'SJ', 	'SJM', 	744, 	'Svalbard & Jan Mayen Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'SZ', 	'SWZ', 	748, 	'Swaziland', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'SE', 	'SWE', 	752, 	'Sweden', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'CH', 	'CHE', 	756, 	'Switzerland', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'SY', 	'SYR', 	760, 	'Syria', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'TJ', 	'TJK', 	762, 	'Tajikistan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'TH', 	'THA', 	764, 	'Thailand', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'TG', 	'TGO', 	768, 	'Togo', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'TK', 	'TKL', 	772, 	'Tokelau', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'TO', 	'TON', 	776, 	'Tonga', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'TT', 	'TTO', 	780, 	'Trinidad and Tobago', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'AE', 	'ARE', 	784, 	'United Arab Emirates', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'TN', 	'TUN', 	788, 	'Tunisia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'TR', 	'TUR', 	792, 	'Turkey', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'TM', 	'TKM', 	795, 	'Turkmenistan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'TC', 	'TCA', 	796, 	'Turks and Caicos Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'TV', 	'TUV', 	798, 	'Tuvalu', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'UG', 	'UGA', 	800, 	'Uganda', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'UA', 	'UKR', 	804, 	'Ukraine', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'MK', 	'MKD', 	807, 	'Macedonia', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'EG', 	'EGY', 	818, 	'Egypt', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'GB', 	'GBR', 	826, 	'United Kingdom', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'GG', 	'GGY', 	831, 	'Guernsey', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'JE', 	'JEY', 	832, 	'Jersey', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XEU', 	'IM', 	'IMN', 	833, 	'Isle of Man', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'TZ', 	'TZA', 	834, 	'Tanzania', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'US', 	'USA', 	840, 	'United States of America', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XNA', 	'VI', 	'VIR', 	850, 	'United States Virgin Islands', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'BF', 	'BFA', 	854, 	'Burkina Faso', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'UY', 	'URY', 	858, 	'Uruguay', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'UZ', 	'UZB', 	860, 	'Uzbekistan', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XSA', 	'VE', 	'VEN', 	862, 	'Venezuela', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'WF', 	'WLF', 	876, 	'Wallis and Futuna', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XOC', 	'WS', 	'WSM', 	882, 	'Samoa', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAS', 	'YE', 	'YEM', 	887, 	'Yemen', 2);
INSERT INTO countries (parent, alpha2, alpha3, numeric, label, level) VALUES ('XAF', 	'ZM', 	'ZMB', 	894, 	'Zambia', 2);